#!/usr/bin/env bash
# View or fix alembic migration chains across the repo.

cmd_migrations() {
  require_repo
  local sub=${1:-status}
  shift 2>/dev/null || true

  case "$sub" in
    status|heads|""|ls|list)
      _migrations_print_status
      ;;
    fix|linearize)
      _migrations_run_fix "$@"
      ;;
    *)
      die "usage: supercode migrations [status|fix [--no-commit]]"
      ;;
  esac
}

_migrations_print_status() {
  local any=0
  local dir
  while IFS= read -r dir; do
    [[ -z "$dir" ]] && continue
    any=1
    local rel="${dir#$REPO_ROOT/}"
    local heads forks head_count
    heads=$(migrations_heads "$dir")
    forks=$(migrations_fork_points "$dir")
    head_count=$(echo "$heads" | grep -c '.' || true)

    echo "${C_BOLD}${rel}${C_RESET}"
    if (( head_count <= 1 )) && [[ -z "$forks" ]]; then
      ok "linear chain, head: $(echo "$heads" | head -1)"
    else
      if (( head_count > 1 )); then
        warn "multiple heads ($head_count):"
        echo "$heads" | sed 's/^/      /'
      fi
      if [[ -n "$forks" ]]; then
        warn "fork points:"
        echo "$forks" | sed 's/^/      /'
      fi
      echo "    ${C_DIM}fix with:${C_RESET} supercode migrations fix"
    fi
  done < <(migrations_find_dirs "$REPO_ROOT")

  (( any )) || info "no alembic versions/ directories found"
}

_migrations_run_fix() {
  local no_commit=0
  while (( $# )); do
    case "$1" in
      --no-commit) no_commit=1; shift ;;
      *) shift ;;
    esac
  done

  # Refuse to rewrite while there are uncommitted changes — would muddle
  # the fix commit with unrelated edits.
  if ! git -C "$REPO_ROOT" diff --quiet 2>/dev/null \
     || ! git -C "$REPO_ROOT" diff --cached --quiet 2>/dev/null; then
    die "working tree has uncommitted changes -- commit or stash first"
  fi

  local total_edits=0
  local touched_dirs=()
  local dir
  while IFS= read -r dir; do
    [[ -z "$dir" ]] && continue
    local edits
    if edits=$(migrations_linearize_dir "$dir" 2>/dev/null); then
      local rel="${dir#$REPO_ROOT/}"
      ok "${rel}: $edits edit(s)"
      total_edits=$(( total_edits + edits ))
      touched_dirs+=("$dir")
    fi
  done < <(migrations_find_dirs "$REPO_ROOT")

  if (( total_edits == 0 )); then
    ok "all chains already linear -- nothing to fix"
    return 0
  fi

  if (( no_commit )); then
    info "skipped commit (--no-commit). Stage and commit manually."
    return 0
  fi

  # Stage and commit
  local d
  for d in "${touched_dirs[@]}"; do
    git -C "$REPO_ROOT" add "$d" >/dev/null
  done
  git -C "$REPO_ROOT" -c user.name='supercode' -c user.email='supercode@local' \
    commit -m "fix(alembic): linearize parallel migration chains

Auto-generated by 'supercode migrations fix'. Multiple agents created
migrations against the same down_revision; re-parented children in
git commit-time order so the chain is linear and 'alembic upgrade head'
succeeds." --no-verify >/dev/null

  ok "committed linearization fix"
}
